resources:
- name: demoapp-git-resource
  type: git
  source:
    uri: https://github.com/andifalk/concourse-ci-demo.git
    branch: master
- name: cf-resource
  type: cf
  source:
    api:  https://api.local.pcfdev.io
    username: admin
    password: admin
    organization: pcfdev-org
    space: pcfdev-space
    skip_cert_check: true

jobs:
- name: build-job
  plan:
    - get: demoapp-git-resource
      trigger: true
    - task: build
      file: demoapp-git-resource/demo-app/ci/task-build.yml
    - put: cf-resource
      params:
        manifest: demoapp-git-resource/demo-app/cf/manifest.yml
        path: deploy-artifact/demo-app-1.0.0-SNAPSHOT.jar
              