resource_types:
- name: cf-event-type
  type: docker-image
  source:
    repository: mevansam/cf-event
    tag: latest
- name: slack-alert
  type: docker-image
  source:
    repository: arbourd/concourse-slack-alert-resource    

resources:
- name: demoapp-git-resource
  type: git
  source:
    uri: https://github.com/andifalk/concourse-ci-demo.git
    branch: master
- name: cf-resource
  type: cf
  source:
    api:  https://api.local.pcfdev.io
    username: ((pcf_user))
    password: ((pcf_password))
    organization: pcfdev-org
    space: pcfdev-space
    skip_cert_check: true
- name: cf-event-resource
  type: cf-event-type
  source:
    api: https://api.local.pcfdev.io
    user: ((pcf_user))
    password: ((pcf_password))
    org: pcfdev-org
    space: pcfdev-space
    skip-ssl-validation: true
    apps:
    - concourse-demo
- name: notify
  type: slack-alert
  source:
    url: ((slack-hook))
    channel: '#notifications'  

groups:
- name: build
  jobs:
  - build-job
- name: test
  jobs:
  - scan-job  

jobs:
- name: build-job
  plan:
    - get: demoapp-git-resource
      trigger: true
    - task: build
      file: demoapp-git-resource/demo-app/ci/task-build.yml
    - put: cf-resource
      params:
        manifest: demoapp-git-resource/demo-app/cf/manifest.yml
        path: deploy-artifact/demo-app-1.0.0-SNAPSHOT.jar
- name: scan-job
  plan:
    - get: cf-event-resource
    - get: demoapp-git-resource
      passed: [build-job]
      trigger: true
    - task: baseline-scan
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: owasp/zap2docker-weekly}
        inputs:
        - name: cf-event-resource  
        run:
          path: zap-cli
          args:
          - quick-scan 
          - --self-contained
          - --start-options 
          - '-config api.disablekey=true'  
          - --spider
          - --scanners
          - all
          - --recursive
          - --alert-level
          - Informational
          - http://concourse-demo.local.pcfdev.io/
      on_success:
        put: notify
        params:
          alert_type: success
      on_failure:
        put: notify
        params:
          alert_type: failed
      on_abort:
        put: notify
        params:
          alert_type: aborted
            
