resources:
- name: myschedule
  type: time
  source: {interval: 30s}

jobs:
- name: hello-world-job
  plan:
  - get: myschedule
    trigger: true 
  - task: say-hello
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: alpine}
      run:
        path: echo
        args: ["Hello World!"]
