version: '3'

services:
  # Cloud Foundry UAA
  uaa:
    image: pcfseceng/uaa
    volumes:
      - ./uaa.yml:/uaa/uaa.yml
    ports:
    - 8090:8080
    restart: always

  # CloudFoundry CredHub
  credhub:
    image: orangeopensource/credhub
    ports:
      - "9000:9000"
    links:
      - uaa:uaa
    depends_on:
      - uaa
    environment:
      UAA_URL: http://uaa:8080/uaa
      UAA_INTERNAL_URL: http://uaa:8080/uaa

  # JFrog Artifactory OSS
  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss:6.4.1
    container_name: artifactory
    ports:
     - 8081:8081
    volumes:
     - /data/artifactory:/var/opt/jfrog/artifactory
#    environment:
#     - EXTRA_JAVA_OPTIONS=-Xmx4g
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000

  # PostgreSQL for Concourse CI
  concourse-db:
    image: postgres
    environment:
    - POSTGRES_DB=concourse
    - POSTGRES_PASSWORD=concourse_pass
    - POSTGRES_USER=concourse_user
    - PGDATA=/database

  # Concourse CI
  concourse:
    image: concourse/concourse
    command: quickstart
    privileged: true
    depends_on: [concourse-db, credhub, artifactory]
    ports: ["8080:8080"]
    links:
      - artifactory:artifactory
      - credhub:credhub
    environment:
    - CONCOURSE_POSTGRES_HOST=concourse-db
    - CONCOURSE_POSTGRES_USER=concourse_user
    - CONCOURSE_POSTGRES_PASSWORD=concourse_pass
    - CONCOURSE_POSTGRES_DATABASE=concourse
    - CONCOURSE_EXTERNAL_URL
    - CONCOURSE_ADD_LOCAL_USER=test:$$2a$$10$$0W9/ilCpYXY/yCPpaOD.6eCrGda/fnH3D4lhsw1Mze0WTID5BuiTW
    - CONCOURSE_MAIN_TEAM_ALLOW_ALL_USERS=true
    - CONCOURSE_WORKER_GARDEN_NETWORK
    - CONCOURSE_CREDHUB_URL=https://credhub:9000
    - CONCOURSE_CREDHUB_INSECURE_SKIP_VERIFY=true
    - CONCOURSE_CREDHUB_CLIENT_ID=credhub_client
    - CONCOURSE_CREDHUB_CLIENT_SECRET=secret
